### ISSUE TITLE
Exercises Tracking Issue

### ISSUE THREAD

**Issue by francisfuzz** [francisfuzz/react-hooks#2]
## Summary

Inspired by Gregor's issue in https://github.com/gr2m/react-fundamentals/issues/1 ✌️ 

- [x] [useState: greeting](https://github.com/francisfuzz/react-hooks/pull/4)
- [x] [useEffect: persistent state](https://github.com/francisfuzz/react-hooks/pull/3)
- [x] [Lifting state](https://github.com/francisfuzz/react-hooks/pull/5)
- [x] [useState: tic tac toe](https://github.com/francisfuzz/react-hooks/pull/1)
- [x] [useRef and useEffect: DOM interaction](https://github.com/francisfuzz/react-hooks/pull/6)
- [x] useEffect: HTTP requests

**Comment by francisfuzz** [comment]
💐  This is finished!
